server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://backend-auth-service-ws-solutions:8080
              predicates:
                - Path=/auth/**,/users/**
              filters:
                - RemoveRequestHeader=Cookie
                - PreserveHostHeader

            - id: person-service
              uri: http://backend-person-service-ws-solutions:8080
              predicates:
                - Path=/person/**
              filters:
                - RemoveRequestHeader=Cookie
                - PreserveHostHeader

            - id: property-service
              uri: http://backend-property-service-ws-solutions:8080
              predicates:
                - Path=/property/**
              filters:
                - RemoveRequestHeader=Cookie
                - PreserveHostHeader